name: madeira
description: "A new Flutter project."

publish_to: 'none' 

version: 1.1.0+2

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # UI and styling
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  
  # Network and API
  http: ^1.1.0
  http_parser: ^4.0.2
  cached_network_image: ^3.4.0
  dio: ^5.4.1
  
  # Utils
  intl: ^0.20.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  carousel_slider: ^4.2.1
  image_picker: ^1.1.2
  flutter_sound: ^9.2.13
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  get: ^4.6.6

  # Firebase
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
